CREATE TABLE IF NOT EXISTS public.ereferral
(
    referral_id SERIAL PRIMARY KEY,
    e_referral_id VARCHAR(255) NOT NULL UNIQUE,
    referral_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    clinician_name VARCHAR(255),
    clinician_contact_details VARCHAR(20),
    healthcare_provider_number VARCHAR(50),
    practice_name VARCHAR(255),
    practice_contact_details VARCHAR(20),
    secure_messaging_provider VARCHAR(255),
    secure_messaging_endpoint VARCHAR(255),
    patient_first_name VARCHAR(255),
    patient_last_name VARCHAR(255),
    patient_contact_details VARCHAR(20),
    patient_alternate_contact_name VARCHAR(255),
    patient_alternate_contact_details VARCHAR(20),
    target_organisation_name VARCHAR(255),
    target_faculty VARCHAR(255),
    referral_reason TEXT,
    medication_history TEXT,
    comorbidity TEXT,
    patient_dob DATE,
    medicare_number VARCHAR(15),
    medicare_expiry DATE,
    atsi_code INTEGER,
    primary_language_code INTEGER,
    additional_info TEXT,
    patient_full_address TEXT,
    patient_email VARCHAR(255),
    patient_postcode VARCHAR(4),
    patient_state VARCHAR(3),
    referral_status INTEGER, -- Added: Referral status as an integer
    referral_accepted_rejected_date TIMESTAMP WITH TIME ZONE -- Added: Date when referral was accepted
);
